# Generated by Django 2.1.1 on 2018-11-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_beneficiarios_observacion'),
        ('operativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrega_especial', models.BooleanField(default=False)),
                ('comision_servicio', models.BooleanField(default=False)),
                ('numero_bolsas', models.IntegerField(default=1)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiarios')),
            ],
        ),
        migrations.RemoveField(
            model_name='operativo',
            name='beneficiario',
        ),
        migrations.AddField(
            model_name='entrega',
            name='operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operativos.Operativo'),
        ),
    ]
