# Generated by Django 2.1.1 on 2018-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0002_auto_20181106_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='comision_servicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='entrega_especial',
            field=models.IntegerField(default=0),
        ),
    ]
