# Generated by Django 2.1.1 on 2018-11-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0004_operativfdo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operativfdo',
        ),
    ]
