# Generated by Django 2.1.1 on 2018-11-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0005_delete_operativfdo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='entrega_especial',
        ),
        migrations.AddField(
            model_name='entrega',
            name='observacion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
