# Generated by Django 2.1.1 on 2018-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativos', '0007_auto_20181109_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='especial',
            field=models.IntegerField(default=0),
        ),
    ]
