# Generated by Django 2.1.1 on 2018-10-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('cedula', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.CharField(default='', max_length=255)),
                ('cargo', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
